spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:product-management-ex}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
server:
  servlet:
    context-path: /product-management-ex
